# Generated by Django 3.1.12 on 2025-08-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentprofile',
            name='experience',
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Enter your years of experience', null=True),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Enter your skills, separated by commas (e.g., Python, Django, React)'),
        ),
    ]
