# Generated by Django 3.1.12 on 2025-08-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
