# Generated by Django 3.1.12 on 2025-08-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0005_auto_20250827_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='professional_background',
            field=models.TextField(blank=True, help_text='A brief summary of your professional background and career highlights.'),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='availability',
            field=models.CharField(choices=[('Remote', 'Remote'), ('In-Office', 'In-Office'), ('Hybrid', 'Hybrid')], default='Remote', max_length=20),
        ),
    ]
