# Generated by Django 3.1.12 on 2025-08-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0007_project_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actual_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='skill_complexity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
