# Generated by Django 3.1.12 on 2025-08-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0009_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
