# Generated by Django 3.1.12 on 2025-08-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0010_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
