# Generated by Django 3.1.12 on 2025-08-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0012_userpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='actual_budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skill_complexity',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_hours',
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Full-Time', 'Full-Time'), ('Freelancer', 'Freelancer'), ('Client', 'Client')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='UserPassword',
        ),
    ]
