# Generated by Django 3.1.12 on 2025-09-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0014_auto_20250828_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
