# Generated by Django 3.1.12 on 2025-09-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0016_auto_20250902_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='skill_complexity',
            new_name='estimated_hours',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_hours',
        ),
        migrations.AddField(
            model_name='project',
            name='complexity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Fixed Price', 'Fixed Price'), ('Hourly', 'Hourly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='required_skills',
            field=models.TextField(help_text='Comma-separated skills'),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='professional_background',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
