# Generated by Django 3.1.12 on 2025-09-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0018_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='availability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
