# Generated by Django 3.1.12 on 2025-09-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0019_auto_20250904_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('full_time', 'Full-Time'), ('freelancer', 'Freelancer'), ('client', 'Client')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='availability',
            field=models.CharField(blank=True, choices=[('Remote', 'Remote'), ('In-Office', 'In-Office'), ('Hybrid', 'Hybrid')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='TalentProfile',
        ),
    ]
