# Generated by Django 3.1.12 on 2025-09-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0020_auto_20250904_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_strength',
            field=models.IntegerField(default=0),
        ),
    ]
