# Generated by Django 3.1.12 on 2025-09-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0021_profile_profile_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('full_time', 'Full Time')], default='freelancer', max_length=20),
        ),
    ]
