# Generated by Django 3.1.12 on 2025-09-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0022_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='complexity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('web', 'Web Application'), ('mobile', 'Mobile Application'), ('data', 'Data Analytics'), ('cyber', 'Cybersecurity')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='open', max_length=20),
        ),
    ]
