# Generated by Django 3.1.12 on 2025-09-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0023_auto_20250905_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='complexity',
        ),
    ]
