# Generated by Django 3.1.12 on 2025-09-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0024_remove_project_complexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('web', 'Web Application'), ('mobile', 'Mobile Application'), ('data', 'Data Science'), ('cyber', 'Cybersecurity'), ('ui', 'UI/UX Design')], max_length=20),
        ),
    ]
