# Generated by Django 3.1.12 on 2025-09-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0028_auto_20250910_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='systemstats',
            name='total_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
