# Generated by Django 3.1.12 on 2025-09-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0031_progressupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
