# Generated by Django 3.1.12 on 2025-09-15 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0033_projectearnings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='user_name',
        ),
    ]
