# Generated by Django 3.1.12 on 2025-09-15 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0034_auto_20250915_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
    ]
