# Generated by Django 3.1.12 on 2025-09-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0035_remove_profile_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
